Repository nextcloud/previewgenerator, pull requests merged in 2022-02, with the labels that each got.

#287 Bump setup-php to v2
  .github/workflows/lint.yml
Labels: 3. to review

#286 Add support for php v8.1
  .github/workflows/lint.yml
  appinfo/info.xml
Labels: enhancement, 2. developing

#288 Suggest setting memory_limit via environment variable
  README.md
Labels: enhancement, 3. to review
