Repository nextcloud/previewgenerator, pull requests merged in 2023-04, with the labels that each got.

#365 use {$var} instead of ${var}
  lib/Command/PreGenerate.php
Labels: 4. to release, techdebt

#367 fix: deprecation warning about curly braces in strings
  lib/Command/Generate.php
Labels: backport-request, 4. to release, techdebt

#376 fix: skip deleted files
  lib/Command/PreGenerate.php
Labels: bug, 3. to review

#383 fix: improve trash bin detection error handling
  lib/Command/PreGenerate.php
Labels: backport-request
